name: Behave Tests with Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          pip install -r requirements.txt
          pip install allure-behave

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Run tests
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          .\run_parallel_in_chrome.ps1

      - name: Generate Allure report
        if: always()
        run: allure generate reports/allure-results --clean -o reports/allure-report

      - name: Setup GitHub Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload report artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
